### ISSUE TITLE
Requesting new scripts

### ISSUE THREAD

**Issue by jennijuju** [jeff-aion/UnityBootstrap#1]
0. Updating meta-data.

1. For `getSelfBondStake`/`getStake`/`getPoolStatus`/`isActive`:
    Use case: pool operator wants to check if the pool is active or not. If not, they can adjust the self-bonded stake to make sure that the pool is active.

2. For `getSigningAddress`:
    Use case: pool operator forgets the signing address they used for a pool and they need it for signing the block.
(Using scripts with event listening will be fine, but we need to set up the events they need to listen to for getting this information. )

3. For `getCoinbaseAddressForSigning/IdentityAddress`:
    Use case: pool operator wants to see if they win the reward(PoS) or not.

**Comment by jennijuju** [comment]
Also requesting scripts for:

**Comment by aion-shidokht** [comment]
Items in this issue are either outdated or covered in the delegation interface.
